-- INITIALIZE
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE SCD2_DB;
USE DATABASE SCD2_DB;

-- BRONZE LAYER
CREATE OR REPLACE SCHEMA BRONZE;
USE SCHEMA BRONZE;

-- GRANT SCHEMA PRIVILEGES
GRANT USAGE ON DATABASE SCD2_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA SCD2_DB.BRONZE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA SCD2_DB.BRONZE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCD2_DB.BRONZE TO ROLE ACCOUNTADMIN;

-- CREATING S3 INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION SCD2_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::000185048470:role/p4_scd2_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://p4-scd2-bucket/raw_data/');

DESC INTEGRATION SCD2_INT;

-- -------------------------------------------------------------------------------
-- GIVE PRIVILEGES: 
-- -------------------------------------------------------------------------------
-- NO NEED
-- -------------------------------------------------------------------------------
-- 1. Grant privileges on database SCD2_DB to PC_DBT_ROLE
-- Database-level privileges
GRANT MODIFY ON DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;
GRANT USAGE ON DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;

-- Future object privileges (database)
GRANT DELETE ON FUTURE TABLES IN DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;
GRANT OWNERSHIP ON FUTURE STAGES IN DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;
GRANT READ ON FUTURE STAGES IN DATABASE SCD2_DB TO ROLE PC_DBT_ROLE;

-- 2. Grant privileges on schema BRONZE inside SCD2_DB
-- Schema-level privileges
GRANT USAGE ON SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT MODIFY ON SCHEMA BRONZE TO ROLE PC_DBT_ROLE;

-- Future object privileges (schema)
GRANT INSERT ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT DELETE ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT READ ON FUTURE STAGES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BRONZE TO ROLE PC_DBT_ROLE;

-- 3. Grant privileges on stage SCD2_STAGE
-- Stage privilege
GRANT USAGE ON STAGE SCD2_STAGE TO ROLE PC_DBT_ROLE;
-- -------------------------------------------------------------------------------

-- CREATING CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;

-- CREATING EXTERNAL STAGE
CREATE OR REPLACE STAGE SCD2_DB.BRONZE.SCD2_STAGE 
  STORAGE_INTEGRATION = SCD2_INT
  URL = 's3://p4-scd2-bucket/raw_data/'
  FILE_FORMAT = MY_CSV_FORMAT;

LIST @SCD2_DB.BRONZE.SCD2_STAGE;

-- CREATING BRONZE LAYER RAW TABLE
CREATE OR REPLACE TABLE SCD2_DB.BRONZE.WORK_PRODUCT_COPY (
    PRODUCT_ID VARCHAR(255) NOT NULL COLLATE 'en-ci',
    PRODUCT_NAME VARCHAR(255) NOT NULL COLLATE 'en-ci',
    CATEGORY VARCHAR(255) COLLATE 'en-ci',
    SELLING_PRICE VARCHAR(50) COLLATE 'en-ci',
    MODEL_NUMBER VARCHAR(50) COLLATE 'en-ci',
    ABOUT_PRODUCT VARCHAR(5000) COLLATE 'en-ci',
    PRODUCT_SPECIFICATION VARCHAR(5000) COLLATE 'en-ci',
    TECHNICAL_DETAILS VARCHAR(50000) COLLATE 'en-ci',
    SHIPPING_WEIGHT VARCHAR(30) COLLATE 'en-ci',
    PRODUCT_DIMENSIONS VARCHAR(100) COLLATE 'en-ci',
    INSERT_DTS TIMESTAMP_NTZ(6) NOT NULL,
    UPDATE_DTS TIMESTAMP_NTZ(6) NOT NULL,
    SOURCE_FILE_NAME VARCHAR(255) NOT NULL,
    SOURCE_FILE_ROW_NUMBER VARCHAR(255) NOT NULL);

-- CHECK DATA IN SNAPSHOT
SELECT * FROM SNAPSHOTS.PRODUCT_SNAPSHOT;

-- GOLD LAYER
SELECT * FROM SCD2_DB.GOLD.PRODUCT_VIEW;

-- DEMONESTRATION
SELECT * FROM SCD2_DB.GOLD.PRODUCT_VIEW
WHERE PRODUCT_ID = '4c69b61db1fc16e7013b43fc926e502d';
