## Snowflake codes:

-- INITIALIZING
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE MYDB;
USE SCHEMA PUBLIC;

-- CREATING S3 INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::000185048470:role/p1_snowpipe_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://p1-realtime-data-bucket/data/');

DESC INTEGRATION S3_INT;

-- CREATING EXTERNAL STAGE
CREATE OR REPLACE STAGE MYDB.PUBLIC.S3_STAGE
STORAGE_INTEGRATION = S3_INT
URL= 's3://p1-realtime-data-bucket/data/';

LIST @MYDB.PUBLIC.S3_STAGE;

-- CREATING A NEW DESTINATION TABLE
CREATE OR REPLACE TABLE MYDB.PUBLIC.MYTABLE
(DATA VARIANT);

SELECT * FROM MYDB.PUBLIC.MYTABLE;

-- CREATING SNOWPIPE
CREATE OR REPLACE PIPE MYDB.PUBLIC.MYPIPE AUTO_INGEST = TRUE AS
COPY INTO MYDB.PUBLIC.MYTABLE
FROM @MYDB.PUBLIC.S3_STAGE
FILE_FORMAT = (TYPE = 'JSON');

SHOW PIPES;

-- CHECK RESULTS
SELECT * FROM MYDB.PUBLIC.MYTABLE;
