-- INITIALIZING
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE GLUEDB;

-- CREATING S3 INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION GLUE_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::000185048470:role/p2_snowflake_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://p2-glue-bucket/data/');

DESC INTEGRATION GLUE_S3_INT;

-- CREATING EXTERNAL STAGE
CREATE OR REPLACE STAGE GLUEDB.PUBLIC.GLUE_S3_STAGE
STORAGE_INTEGRATION = GLUE_S3_INT
URL= 's3://p2-glue-bucket/data/';

LS @GLUEDB.PUBLIC.GLUE_S3_STAGE;

-- CREATING A NEW DESTINATION TABLE
CREATE OR REPLACE TABLE GLUEDB.PUBLIC.COUNTRY_DETAILS_CP
(DATA VARIANT);

SELECT * FROM GLUEDB.PUBLIC.COUNTRY_DETAILS_CP;

-- BRONZE (RAW) LAYER
SELECT * FROM GLUEDB.RAW.COUNTRY_DETAILS_RAW;

-- SILVER (TRANSFORM) LAYER
SELECT * FROM GLUEDB.TRANSFORM.COUNTRY_DETAILS_TRANSFORM;

-- GOLD (MART) LAYER
SELECT DISTINCT COUNTRY_CONTINENT_NAME FROM GLUEDB.TRANSFORM.COUNTRY_DETAILS_TRANSFORM;

SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_AFRICA;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_ANTARCTICA;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_ASIA;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_EUROPE;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_NORTH_AMERICA;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_OCEANIA;
SELECT * FROM GLUEDB.MART.COUNTRY_DETAILS_SOUTH_AMERICA;

-- JOB CREATION
CREATE OR REPLACE DATABASE GLUEDB_PRODUCTION;

SELECT 
    TABLE_NAME, 
    ROW_COUNT
FROM 
    INFORMATION_SCHEMA.TABLES
WHERE 
    TABLE_CATALOG = 'GLUEDB_PRODUCTION'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY 
    TABLE_NAME;
